-- MySQL Script generated by MySQL Workbench
-- Sat Oct  8 16:53:26 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ingenieria
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ingenieria` ;

-- -----------------------------------------------------
-- Schema ingenieria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ingenieria` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `ingenieria` ;

-- -----------------------------------------------------
-- Table `ingenieria`.`Documento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ingenieria`.`Documento` ;

CREATE TABLE IF NOT EXISTS `ingenieria`.`Documento` (
  `idDocumento` INT NOT NULL COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idDocumento`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ingenieria`.`Motivo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ingenieria`.`Motivo` ;

CREATE TABLE IF NOT EXISTS `ingenieria`.`Motivo` (
  `idMotivo` INT NOT NULL COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idMotivo`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ingenieria`.`Estudiante/Egresado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ingenieria`.`Estudiante/Egresado` ;

CREATE TABLE IF NOT EXISTS `ingenieria`.`Estudiante/Egresado` (
  `boleta` VARCHAR(10) NOT NULL COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `Semestre` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`boleta`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ingenieria`.`Tramite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ingenieria`.`Tramite` ;

CREATE TABLE IF NOT EXISTS `ingenieria`.`Tramite` (
  `idTrámites` INT NOT NULL COMMENT '',
  `Documento_idDocumento` INT NOT NULL COMMENT '',
  `Motivo_idMotivo` INT NOT NULL COMMENT '',
  `solicitante` VARCHAR(10) NOT NULL COMMENT '',
  PRIMARY KEY (`idTrámites`)  COMMENT '',
  INDEX `fk_Tramite_Documento1_idx` (`Documento_idDocumento` ASC)  COMMENT '',
  INDEX `fk_Tramite_Motivo1_idx` (`Motivo_idMotivo` ASC)  COMMENT '',
  INDEX `fk_Tramite_Estudiante/Egresado1_idx` (`solicitante` ASC)  COMMENT '',
  CONSTRAINT `fk_Tramite_Documento1`
    FOREIGN KEY (`Documento_idDocumento`)
    REFERENCES `ingenieria`.`Documento` (`idDocumento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tramite_Motivo1`
    FOREIGN KEY (`Motivo_idMotivo`)
    REFERENCES `ingenieria`.`Motivo` (`idMotivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tramite_Estudiante/Egresado1`
    FOREIGN KEY (`solicitante`)
    REFERENCES `ingenieria`.`Estudiante/Egresado` (`boleta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
